import type { VideoPair } from "./types";

const defaultQA = { cameraPosition: false, lighting: false, oneChange: false, duration: false, resolution: false, stableCamera: false, noOutfitChange: false, noFilters: false, naming: false };

export const initialPairs: VideoPair[] = [
  // === OBJECT CHANGE (1-27) ===
  {
    id: "p1", pairNumber: 1, type: "Object Change",
    description: "Film a kitchen counter with a mug → remove the mug, film again",
    fullInstructions: "Film a kitchen counter with a mug → remove the mug, film again. Ensure the camera angle, lighting, and framing are identical between both shots. The ONLY difference should be the presence/absence of the mug.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p2", pairNumber: 2, type: "Object Change",
    description: "Film a table with a plate of food → remove the plate, film again",
    fullInstructions: "Film a table with a plate of food → remove the plate, film again. Keep camera position, lighting, and background completely unchanged.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p3", pairNumber: 3, type: "Object Change",
    description: "Film a counter with a water bottle → replace with a glass, film again",
    fullInstructions: "Film a counter with a water bottle → replace with a glass, film again. Maintain identical framing and lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p4", pairNumber: 4, type: "Object Change",
    description: "Film a table with a bowl → remove the bowl, film again",
    fullInstructions: "Film a table with a bowl → remove the bowl, film again. Everything except the bowl must remain identical.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p5", pairNumber: 5, type: "Object Change",
    description: "Film a kitchen shelf with a jar → remove the jar, film again",
    fullInstructions: "Film a kitchen shelf with a jar → remove the jar, film again. Keep camera position and lighting identical.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p6", pairNumber: 6, type: "Object Change",
    description: "Film a couch with a pillow → remove the pillow, film again",
    fullInstructions: "Film a couch with a pillow → remove the pillow, film again. Same framing, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p7", pairNumber: 7, type: "Object Change",
    description: "Film a chair with a blanket → remove the blanket, film again",
    fullInstructions: "Film a chair with a blanket draped on it → remove the blanket, film again. Keep everything else identical.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p8", pairNumber: 8, type: "Object Change",
    description: "Film a coffee table with a remote → remove the remote, film again",
    fullInstructions: "Film a coffee table with a TV remote → remove the remote, film again. Same angle, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p9", pairNumber: 9, type: "Object Change",
    description: "Film a shelf with a photo frame → remove the frame, film again",
    fullInstructions: "Film a shelf with a photo frame → remove the frame, film again. Maintain identical framing and lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p10", pairNumber: 10, type: "Object Change",
    description: "Film a table with a vase → remove the vase, film again",
    fullInstructions: "Film a table with a vase → remove the vase, film again. Keep camera and lighting unchanged.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p11", pairNumber: 11, type: "Object Change",
    description: "Film an empty table → add a book, film again",
    fullInstructions: "Film an empty table → add a book to it, film again. Same framing and lighting between both shots.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p12", pairNumber: 12, type: "Object Change",
    description: "Film a couch with a bag on it → remove the bag, film again",
    fullInstructions: "Film a couch with a bag on it → remove the bag, film again. Everything except the bag must remain identical.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p13", pairNumber: 13, type: "Object Change",
    description: "Film a desk with a laptop → replace with a book, film again",
    fullInstructions: "Film a desk with a laptop → replace with a book, film again. Keep camera position, lighting, and background completely unchanged.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p14", pairNumber: 14, type: "Object Change",
    description: "Film a desk with headphones → remove the headphones, film again",
    fullInstructions: "Film a desk with headphones → remove the headphones, film again. Same framing, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p15", pairNumber: 15, type: "Object Change",
    description: "Film a desk with a phone → remove the phone, film again",
    fullInstructions: "Film a desk with a phone → remove the phone, film again. Keep everything else identical.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p16", pairNumber: 16, type: "Object Change",
    description: "Film a desk with a pen → remove the pen, film again",
    fullInstructions: "Film a desk with a pen → remove the pen, film again. Same angle, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p17", pairNumber: 17, type: "Object Change",
    description: "Film a chair with a backpack → remove the backpack, film again",
    fullInstructions: "Film a chair with a backpack → remove the backpack, film again. Maintain identical framing and lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p18", pairNumber: 18, type: "Object Change",
    description: "Film a bed with an extra pillow → remove the pillow, film again",
    fullInstructions: "Film a bed with an extra pillow → remove the pillow, film again. Same framing, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p19", pairNumber: 19, type: "Object Change",
    description: "Film a nightstand with a lamp → remove the lamp, film again",
    fullInstructions: "Film a nightstand with a lamp → remove the lamp, film again. Keep camera and lighting unchanged.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p20", pairNumber: 20, type: "Object Change",
    description: "Film a door with a towel hanging → remove the towel, film again",
    fullInstructions: "Film a door with a towel hanging on it → remove the towel, film again. Same angle, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p21", pairNumber: 21, type: "Object Change",
    description: "Film a bathroom counter with soap → remove the soap, film again",
    fullInstructions: "Film a bathroom counter with soap → remove the soap, film again. Everything except the soap must remain identical.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p22", pairNumber: 22, type: "Object Change",
    description: "Film a bed with a folded shirt → remove the shirt, film again",
    fullInstructions: "Film a bed with a folded shirt → remove the shirt, film again. Maintain identical framing and lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p23", pairNumber: 23, type: "Object Change",
    description: "Film a table with sunglasses → remove the sunglasses, film again",
    fullInstructions: "Film a table with sunglasses → remove the sunglasses, film again. Same framing, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p24", pairNumber: 24, type: "Object Change",
    description: "Film a wall with a hat on a hook → remove the hat, film again",
    fullInstructions: "Film a wall with a hat on a hook → remove the hat, film again. Keep camera and lighting unchanged.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p25", pairNumber: 25, type: "Object Change",
    description: "Film a doorway with shoes → remove the shoes, film again",
    fullInstructions: "Film a doorway with shoes → remove the shoes, film again. Same angle, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p26", pairNumber: 26, type: "Object Change",
    description: "Film a bench with a water bottle → remove the bottle, film again",
    fullInstructions: "Film a bench with a water bottle → remove the bottle, film again. Everything except the bottle must remain identical.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p27", pairNumber: 27, type: "Object Change",
    description: "Film a table with keys → remove the keys, film again",
    fullInstructions: "Film a table with keys → remove the keys, film again. Maintain identical framing and lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },

  // === ACTION CHANGE (28-54) ===
  {
    id: "p28", pairNumber: 28, type: "Action Change",
    description: "Film a person sitting in a chair → stand up, film again (standing)",
    fullInstructions: "Film a person sitting in a chair → stand up, film again (standing). Same camera position, same clothes, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p29", pairNumber: 29, type: "Action Change",
    description: "Film a person with arms down → raise both arms up, film again",
    fullInstructions: "Film a person standing with arms at their sides → raise both arms up, film again. Same spot, same clothes, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p30", pairNumber: 30, type: "Action Change",
    description: "Film a closed door → open the door, film again",
    fullInstructions: "Film a closed door → open the door, film again. Same camera angle, same lighting. Only the door position changes.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p31", pairNumber: 31, type: "Action Change",
    description: "Film a closed book on a table → open the book, film again",
    fullInstructions: "Film a closed book on a table → open the book, film again. Keep camera and lighting unchanged.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p32", pairNumber: 32, type: "Action Change",
    description: "Film a curtain closed → open the curtain, film again",
    fullInstructions: "Film a window with curtain closed → open the curtain, film again. Same camera position. Lighting may change naturally — that is okay.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p33", pairNumber: 33, type: "Action Change",
    description: "Film a light switch OFF → turn it ON, film again",
    fullInstructions: "Film a light switch in the OFF position → flip it ON, film again. Same camera angle. The room lighting will change — that is expected.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p34", pairNumber: 34, type: "Action Change",
    description: "Film a person with eyes open → close eyes, film again",
    fullInstructions: "Film a person's face with eyes open → close eyes, film again. Same position, same expression otherwise, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p35", pairNumber: 35, type: "Action Change",
    description: "Film a fan turned OFF → turn it ON, film again",
    fullInstructions: "Film a ceiling or desk fan turned OFF → turn it ON, film again. Same camera position, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p36", pairNumber: 36, type: "Action Change",
    description: "Film a person with hands in lap → cross arms, film again",
    fullInstructions: "Film a person sitting with hands in lap → cross arms, film again. Same seat, same clothes, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p37", pairNumber: 37, type: "Action Change",
    description: "Film a laptop closed → open it, film again",
    fullInstructions: "Film a closed laptop on a desk → open it, film again. Same camera angle, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p38", pairNumber: 38, type: "Action Change",
    description: "Film an empty glass → pour water into it, film again (full glass)",
    fullInstructions: "Film an empty glass on a table → pour water into it, film again showing the full glass. Same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p39", pairNumber: 39, type: "Action Change",
    description: "Film a person facing the camera → turn around (back to camera), film again",
    fullInstructions: "Film a person facing the camera → turn around so back is to camera, film again. Same spot, same clothes, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p40", pairNumber: 40, type: "Action Change",
    description: "Film a drawer closed → open it, film again",
    fullInstructions: "Film a closed drawer → open it, film again. Same camera position, same lighting. Only the drawer position changes.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p41", pairNumber: 41, type: "Action Change",
    description: "Film a person with no smile → smile, film again",
    fullInstructions: "Film a person's face with a neutral expression → smile, film again. Same position, same lighting. Only the expression changes.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p42", pairNumber: 42, type: "Action Change",
    description: "Film a person standing still → start walking, film again",
    fullInstructions: "Film a person standing still → start walking forward, film again. Same camera position, same clothes, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p43", pairNumber: 43, type: "Action Change",
    description: "Film a person with hair down → tie hair up, film again",
    fullInstructions: "Film a person with hair down → tie hair up in a ponytail or bun, film again. Same position, same clothes, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p44", pairNumber: 44, type: "Action Change",
    description: "Film a rolled-up mat on the floor → unroll it, film again",
    fullInstructions: "Film a rolled-up mat on the floor → unroll it flat, film again. Same camera position, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p45", pairNumber: 45, type: "Action Change",
    description: "Film a person with legs uncrossed → cross legs, film again",
    fullInstructions: "Film a person sitting with legs uncrossed → cross legs, film again. Same seat, same clothes, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p46", pairNumber: 46, type: "Action Change",
    description: "Film a window closed → open it, film again",
    fullInstructions: "Film a closed window → open it, film again. Same camera angle. Outside sounds may change — that is okay.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p47", pairNumber: 47, type: "Action Change",
    description: "Film a person looking left → look right, film again",
    fullInstructions: "Film a person looking to the left → look to the right, film again. Same position, same lighting. Only the head direction changes.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p48", pairNumber: 48, type: "Action Change",
    description: "Film a faucet turned OFF → turn it ON, film again",
    fullInstructions: "Film a faucet turned OFF → turn it ON with water flowing, film again. Same camera position.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p49", pairNumber: 49, type: "Action Change",
    description: "Film a folded towel → unfold it and hang it, film again",
    fullInstructions: "Film a folded towel on a counter → unfold and hang it on a rack, film again. Same camera position, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p50", pairNumber: 50, type: "Action Change",
    description: "Film a person with glasses on → remove glasses, film again",
    fullInstructions: "Film a person wearing glasses → remove glasses, film again. Same position, same clothes, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p51", pairNumber: 51, type: "Action Change",
    description: "Film a person holding a phone → put the phone down, film again",
    fullInstructions: "Film a person holding a phone to their ear → put the phone down on a table, film again. Same position, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p52", pairNumber: 52, type: "Action Change",
    description: "Film a person with sleeves down → roll sleeves up, film again",
    fullInstructions: "Film a person with long sleeves down → roll both sleeves up, film again. Same position, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p53", pairNumber: 53, type: "Action Change",
    description: "Film a chair pushed under desk → pull it out, film again",
    fullInstructions: "Film a chair pushed under a desk → pull it out, film again. Same camera position, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p54", pairNumber: 54, type: "Action Change",
    description: "Film a person with hands flat on table → make fists, film again",
    fullInstructions: "Film a person with hands flat on a table → make fists, film again. Same position, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },

  // === SPEECH CHANGE (55-74) ===
  {
    id: "p55", pairNumber: 55, type: "Speech Change",
    description: "Say 'Hello, my name is [your name]' → say 'Hello, my name is [a different name]'",
    fullInstructions: "Film yourself saying 'Hello, my name is [your real name]' → film again saying 'Hello, my name is [any other name]'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p56", pairNumber: 56, type: "Speech Change",
    description: "Say 'I like cats' → say 'I like dogs'",
    fullInstructions: "Film yourself saying 'I like cats' → film again saying 'I like dogs'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p57", pairNumber: 57, type: "Speech Change",
    description: "Say 'Today is Monday' → say 'Today is Friday'",
    fullInstructions: "Film yourself saying 'Today is Monday' → film again saying 'Today is Friday'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p58", pairNumber: 58, type: "Speech Change",
    description: "Say 'The weather is nice' → say 'The weather is bad'",
    fullInstructions: "Film yourself saying 'The weather is nice today' → film again saying 'The weather is bad today'. Same everything else.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p59", pairNumber: 59, type: "Speech Change",
    description: "Say 'I am going to the store' → say 'I am going to the park'",
    fullInstructions: "Film yourself saying 'I am going to the store' → film again saying 'I am going to the park'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p60", pairNumber: 60, type: "Speech Change",
    description: "Count '1, 2, 3, 4, 5' → count '5, 4, 3, 2, 1'",
    fullInstructions: "Film yourself counting '1, 2, 3, 4, 5' → film again counting '5, 4, 3, 2, 1'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p61", pairNumber: 61, type: "Speech Change",
    description: "Say 'Good morning' → say 'Good night'",
    fullInstructions: "Film yourself saying 'Good morning' → film again saying 'Good night'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p62", pairNumber: 62, type: "Speech Change",
    description: "Say 'I have two brothers' → say 'I have two sisters'",
    fullInstructions: "Film yourself saying 'I have two brothers' → film again saying 'I have two sisters'. Same everything else.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p63", pairNumber: 63, type: "Speech Change",
    description: "Say 'My favorite color is blue' → say 'My favorite color is red'",
    fullInstructions: "Film yourself saying 'My favorite color is blue' → film again saying 'My favorite color is red'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p64", pairNumber: 64, type: "Speech Change",
    description: "Say 'I am happy' → say 'I am tired'",
    fullInstructions: "Film yourself saying 'I am happy' → film again saying 'I am tired'. Same position, same expression, same clothes, same camera.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p65", pairNumber: 65, type: "Speech Change",
    description: "Say 'I want rice' → say 'I want bread'",
    fullInstructions: "Film yourself saying 'I want rice' → film again saying 'I want bread'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p66", pairNumber: 66, type: "Speech Change",
    description: "Say 'The book is on the table' → say 'The book is on the shelf'",
    fullInstructions: "Film yourself saying 'The book is on the table' → film again saying 'The book is on the shelf'. Same everything else.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p67", pairNumber: 67, type: "Speech Change",
    description: "Say 'I live in a house' → say 'I live in an apartment'",
    fullInstructions: "Film yourself saying 'I live in a house' → film again saying 'I live in an apartment'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p68", pairNumber: 68, type: "Speech Change",
    description: "Say 'Turn left at the corner' → say 'Turn right at the corner'",
    fullInstructions: "Film yourself saying 'Turn left at the corner' → film again saying 'Turn right at the corner'. Same everything else.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p69", pairNumber: 69, type: "Speech Change",
    description: "Say 'I woke up at six' → say 'I woke up at nine'",
    fullInstructions: "Film yourself saying 'I woke up at six' → film again saying 'I woke up at nine'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p70", pairNumber: 70, type: "Speech Change",
    description: "Say 'She is my friend' → say 'He is my friend'",
    fullInstructions: "Film yourself saying 'She is my friend' → film again saying 'He is my friend'. Same everything else.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p71", pairNumber: 71, type: "Speech Change",
    description: "Say 'I need a pen' → say 'I need a pencil'",
    fullInstructions: "Film yourself saying 'I need a pen' → film again saying 'I need a pencil'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p72", pairNumber: 72, type: "Speech Change",
    description: "Say 'Open the window' → say 'Close the window'",
    fullInstructions: "Film yourself saying 'Open the window' → film again saying 'Close the window'. Same everything else.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p73", pairNumber: 73, type: "Speech Change",
    description: "Say 'I bought three apples' → say 'I bought three oranges'",
    fullInstructions: "Film yourself saying 'I bought three apples' → film again saying 'I bought three oranges'. Same position, same clothes, same camera, same lighting.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p74", pairNumber: 74, type: "Speech Change",
    description: "Say 'The meeting is at ten' → say 'The meeting is at two'",
    fullInstructions: "Film yourself saying 'The meeting is at ten' → film again saying 'The meeting is at two'. Same everything else.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },

  // === AUDIO CHANGE (75-80) ===
  {
    id: "p75", pairNumber: 75, type: "Audio Change",
    description: "Film a room in silence → play music from a phone, film again",
    fullInstructions: "Film a room in silence (no sound) → play music from a phone speaker, film again. Same camera position, same lighting. Only the background audio changes.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p76", pairNumber: 76, type: "Audio Change",
    description: "Film a quiet kitchen → turn on the faucet for water sound, film again",
    fullInstructions: "Film a quiet kitchen → turn on the faucet so water is running, film again. Same camera position. Only the water sound is different.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p77", pairNumber: 77, type: "Audio Change",
    description: "Film a quiet room → turn on a fan, film again",
    fullInstructions: "Film a quiet room → turn on a fan so you hear the fan noise, film again. Same camera position, same lighting. Only the fan sound is different.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p78", pairNumber: 78, type: "Audio Change",
    description: "Film a person clapping → film same person snapping fingers",
    fullInstructions: "Film a person clapping hands → film again with same person snapping fingers. Same position, same camera, same lighting. Only the sound changes.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p79", pairNumber: 79, type: "Audio Change",
    description: "Film a person tapping a table → film same person tapping a glass",
    fullInstructions: "Film a person tapping their fingers on a wooden table → film again tapping on a glass. Same camera, same lighting. Only the tapping sound is different.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
  {
    id: "p80", pairNumber: 80, type: "Audio Change",
    description: "Film a quiet room → open a window for outside noise, film again",
    fullInstructions: "Film a quiet room with window closed → open the window so outside sounds come in, film again. Same camera position. Only the background noise changes.",
    assignedVA: null, stage: "needs_assignment", dueDate: "2026-03-07", driveLink: "", notes: "", videoAUploaded: false, videoBUploaded: false, qaChecklist: { ...defaultQA },
  },
];
